Bugfix: Can't split empty array
fixes Issue when ENV['GITHUB_REPOSITORIES'] is nil. Cannot split array. Fallback should probably be empty string rather than array.

```
/Users/johnrandall/code/vendor/task_bridge/lib/task_bridge.rb:35:in `block in initialize': undefined method `split' for []:Array (NoMethodError)

      opt :repositories, "Github repositories to sync from", default: ENV.fetch("GITHUB_REPOSITORIES", []).split(",")
                                                                                                          ^^^^^^
	from /Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/optimist-3.0.1/lib/optimist.rb:103:in `call'
	from /Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/optimist-3.0.1/lib/optimist.rb:103:in `initialize'
	from /Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/optimist-3.0.1/lib/optimist.rb:921:in `new'
	from /Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/optimist-3.0.1/lib/optimist.rb:921:in `options'
	from /Users/johnrandall/code/vendor/task_bridge/lib/task_bridge.rb:20:in `initialize'
	from bin/task_bridge:6:in `new'
	from bin/task_bridge:6:in `<main>'
```